# Generated by Django 3.2.20 on 2023-08-12 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='30 characters', max_length=30, verbose_name='Name')),
                ('channel', models.CharField(help_text='9 character token', max_length=9, unique=True, verbose_name='Channel')),
                ('description', models.TextField(blank=True, default='', help_text='description', verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channel',
            },
        ),
        migrations.CreateModel(
            name='PostScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', help_text='Message Text', verbose_name='Message Text')),
                ('schedule_datetime', models.DateTimeField(help_text='Ex. 10/01/1900 01:00', verbose_name='Schedule DateTime')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('is_send', models.BooleanField(default=False, help_text='Has been sent', verbose_name='Is Send')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.channelmodel')),
            ],
            options={
                'verbose_name': 'Post Schedule',
                'verbose_name_plural': 'Post Schedule',
                'ordering': ['schedule_datetime'],
            },
        ),
    ]
