# Generated by Django 3.2.6 on 2023-08-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postschedulemodel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.channelmodel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='postschedulemodel',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='Is Send'),
        ),
        migrations.AlterField(
            model_name='postschedulemodel',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Message Text'),
        ),
    ]
