# Generated by Django 3.2.6 on 2021-08-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='9 length', max_length=9, unique=True, verbose_name='Channel')),
                ('description', models.TextField(blank=True, default='', help_text='description', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ChatParamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', help_text='Message Text', verbose_name='Message Text')),
                ('schedule_datetime', models.DateTimeField(help_text='Ex. 10/01/1900 01:00', verbose_name='Schedule DateTime')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatparam.channelmodel')),
            ],
            options={
                'ordering': ['schedule_datetime'],
            },
        ),
    ]
