# Generated by Django 3.2.6 on 2021-08-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatparam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelmodel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channel'},
        ),
        migrations.AlterModelOptions(
            name='chatparammodel',
            options={'ordering': ['schedule_datetime'], 'verbose_name': 'Chat Parameters', 'verbose_name_plural': 'Chat Parameters'},
        ),
        migrations.AddField(
            model_name='chatparammodel',
            name='is_send',
            field=models.BooleanField(default=False, help_text='Has been sent', verbose_name='Is Send'),
        ),
    ]
